version: '3.8'
services:
  backend:
    build: ./backend
    ports:
     - "8000:80"
#    volumes:
#     - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/project
#      - /project/node_modules # nötig?