-- Create a user for the photohub application
CREATE USER photohub IDENTIFIED BY admin
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

-- Grant necessary privileges to the photohub user
GRANT CREATE SESSION TO photohub;
GRANT CREATE TABLE TO photohub;
GRANT CREATE SEQUENCE TO photohub;
GRANT CREATE PROCEDURE TO photohub;
GRANT CREATE TRIGGER TO photohub;
GRANT CREATE USER TO photohub;
GRANT ALTER USER TO photohub;
GRANT DROP USER TO photohub;
GRANT CREATE TABLESPACE TO photohub;
GRANT DROP TABLESPACE TO photohub;
GRANT CREATE VIEW TO photohub;
GRANT CREATE MATERIALIZED VIEW TO photohub;
GRANT CREATE INDEX TO photohub;
GRANT CREATE TYPE TO photohub;