-- Drop existing functions
DROP FUNCTION IF EXISTS euclidean_distance;
DROP FUNCTION IF EXISTS euclidean_distance_rgb_hist;

-- Drop existing indexes
DROP INDEX content_title_idx;
DROP INDEX content_description_idx;

-- Drop existing tables in the correct order
DROP TABLE TAGS CASCADE CONSTRAINTS;
DROP TABLE LIKES CASCADE CONSTRAINTS;
DROP TABLE COMMENTS CASCADE CONSTRAINTS;
DROP TABLE ALBUM_PHOTO CASCADE CONSTRAINTS;
DROP TABLE ALBUM CASCADE CONSTRAINTS;
DROP TABLE COLOR_HISTOGRAM CASCADE CONSTRAINTS;
DROP TABLE PHOTO CASCADE CONSTRAINTS;
DROP TABLE CONTENT CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE "USER" CASCADE CONSTRAINTS;