/**
 * FastAPI Photohub Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const FileFormatEnum = {
    Png: 'png',
    Jpeg: 'jpeg'
} as const;
export type FileFormatEnum = typeof FileFormatEnum[keyof typeof FileFormatEnum];

