/**
 * FastAPI Photohub Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const OrientationEnum = {
    Horizontal: 'horizontal',
    Vertical: 'vertical',
    Square: 'square'
} as const;
export type OrientationEnum = typeof OrientationEnum[keyof typeof OrientationEnum];

