/**
 * FastAPI Photohub Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VisibilityEnum } from './visibilityEnum';
import { FileFormatEnum } from './fileFormatEnum';
import { OrientationEnum } from './orientationEnum';


export interface PhotoGetResponse { 
    photo_id: number;
    user_id: number;
    title: string;
    description?: string | null;
    category_id?: number | null;
    location?: string | null;
    camera_model?: string | null;
    capture_date?: string | null;
    upload_date: string;
    visibility: VisibilityEnum;
    orientation: OrientationEnum;
    file_format: FileFormatEnum;
    file_size: number;
    views: number;
    width: number;
    height: number;
}
export namespace PhotoGetResponse {
}


