/**
 * FastAPI Photohub Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateRange } from './dateRange';
import { FileFormatEnum } from './fileFormatEnum';
import { OrientationEnum } from './orientationEnum';
import { RGBColor } from './rGBColor';


export interface PhotoSearchRequest { 
    searchInput?: string | null;
    RgbColor?: RGBColor | null;
    minHeight?: number | null;
    minWidth?: number | null;
    Orientation?: OrientationEnum | null;
    FileFormat?: FileFormatEnum | null;
    Location?: string | null;
    CameraModell?: string | null;
    UploadDate?: DateRange | null;
    CaptureDate?: DateRange | null;
    limit?: number | null;
    offset?: number | null;
}
export namespace PhotoSearchRequest {
}


