/**
 * FastAPI Photohub Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RGBVector { 
    r_target: number;
    g_target: number;
    b_target: number;
}

