/**
 * FastAPI Photohub Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const Visibility = {
    Public: 'public',
    Private: 'private'
} as const;
export type Visibility = typeof Visibility[keyof typeof Visibility];

