/**
 * Photohub Backend Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Item } from '../model/models';
import { PatchedItem } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param item 
     */
    apiItemsCreate(item: Item, extraHttpRequestParams?: any): Observable<Item>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this item.
     */
    apiItemsDestroy(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    apiItemsList(extraHttpRequestParams?: any): Observable<Array<Item>>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this item.
     * @param patchedItem 
     */
    apiItemsPartialUpdate(id: number, patchedItem?: PatchedItem, extraHttpRequestParams?: any): Observable<Item>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this item.
     */
    apiItemsRetrieve(id: number, extraHttpRequestParams?: any): Observable<Item>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this item.
     * @param item 
     */
    apiItemsUpdate(id: number, item: Item, extraHttpRequestParams?: any): Observable<Item>;

}
